
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Cars
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

